### PR TITLE
Remove reference to Flow

### PR DESCRIPTION
**Pull request by bwaidelich**
As this package is independent from Flow, this change removes mention of Flow from the description and removes the custom composer package type

### CODE REVIEW

**Comment by bwaidelich** [comment]
@kdambekalns Not sure about the requires syntax, but I stole it from https://github.com/kdambekalns/swiftmailer/blob/master/composer.json ;)
Didn't test it with 3.0 but I guess it works ;)

**Comment by kdambekalns** [comment]
But… it does not depend on Flow, at all. No?

**Comment by bwaidelich** [comment]
ah, doesnt' it.. indeed :smile: 
In that case I wonder about the composer type ("typo3-flow-package") and description ("Faker for PHP, a Flow package.").. I'll adjust the PR accordingly and you can choose

**Comment by bwaidelich** [comment]
_ping_ :)

**Pull request merged**
